x-uffizzi:
  ingress:
    service: app
    port: 80

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "10000:10000"
      - "20000:20000"
      - "30000:30000"
      - "40000:40000"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN
volumes:
  data:
